name: venue_data
description: "A new Flutter package project."
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  http: ^1.4.0
  injectable: ^2.5.0
  meta: ^1.16.0
  venue_domain:
    path: ../venue_domain
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1

flutter:
  assets:
    - assets/gyms.json
