name: venue_list
description: "Venue list presentation package using clean architecture."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.7.2
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  meta: ^1.16.0
  venue_domain:
    path: ../venue_domain
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1

flutter:
  assets:
    - assets/placeholder.jpg
    - assets/privilee_logo.svg
